import type {
  InputHTMLAttributes,
  ReactNode,
  TextareaHTMLAttributes,
} from 'react';

import type { BaseComponentProps } from '@/components/shared/BaseComponent.types';

/** The two visual variants of the M3 TextField component. */
export type TextFieldVariant = 'filled' | 'outlined';

/**
 * Validation state shown to the user.
 * - `'none'`    — no special state (default colors).
 * - `'error'`   — M3 `error` (border/label/text/icon in `--md-sys-color-error`).
 * - `'success'` / `'warning'` — extension of this library
 *   (`--md-sys-color-success` / `--md-sys-color-warning`), not an official M3 role.
 */
export type TextFieldStatus = 'none' | 'error' | 'success' | 'warning';

interface TextFieldBaseProps extends BaseComponentProps {
  /** Visual style of the field. Defaults to `'filled'`. */
  variant?: TextFieldVariant;
  /** Field label. Always visible (resting or floating) — required by M3. */
  label: string;
  /** Icon rendered before the input/textarea. Decorative. */
  leadingIcon?: ReactNode;
  /** Icon rendered after the input/textarea. */
  trailingIcon?: ReactNode;
  /**
   * When defined, `trailingIcon` is wrapped in an accessible
   * `<button type="button">` (clear, show/hide password, etc.).
   * Requires `trailingIconAriaLabel`.
   */
  onTrailingIconClick?: () => void;
  /** Accessible label for the button generated by `onTrailingIconClick`. */
  trailingIconAriaLabel?: string;
  /**
   * Help/error/success/warning text shown below the field.
   * Color and role (`alert`) are determined by `status`.
   */
  supportingText?: string;
  /** Validation state of the field. Defaults to `'none'`. */
  status?: TextFieldStatus;
  /** Shows "current length / maxLength" next to `supportingText`. Requires `maxLength`. */
  showCharacterCount?: boolean;
}

/**
 * Native attributes exclusive to one element, absent from the other.
 *
 * A plain discriminated union (`multiline?: false` vs `multiline: true`)
 * doesn't reject e.g. `rows` when `multiline` is omitted, because
 * TypeScript's excess-property check on unions only flags a property as
 * excess when it appears in *no* member — and `rows` is valid in the
 * `multiline: true` member. Intersecting each branch with
 * `Partial<Record<OtherBranchOnlyKey, never>>` closes that gap.
 */
type InputOnlyAttributes = Omit<
  InputHTMLAttributes<HTMLInputElement>,
  keyof TextareaHTMLAttributes<HTMLTextAreaElement>
>;
type TextareaOnlyAttributes = Omit<
  TextareaHTMLAttributes<HTMLTextAreaElement>,
  keyof InputHTMLAttributes<HTMLInputElement>
>;

export type TextFieldProps =
  | (TextFieldBaseProps & {
      /** `true` renders a `<textarea>` instead of an `<input>`. Defaults to `false`. */
      multiline?: false;
    } & Omit<InputHTMLAttributes<HTMLInputElement>, 'size'> &
      Partial<Record<keyof TextareaOnlyAttributes, never>>)
  | (TextFieldBaseProps & {
      multiline: true;
    } & Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, 'size'> &
      Partial<Record<keyof InputOnlyAttributes, never>>);
