import type {
  InputHTMLAttributes,
  ReactNode,
  TextareaHTMLAttributes,
} from 'react';

import type { BaseComponentProps } from '@/components/shared/BaseComponent.types';

/** The two visual variants of the M3 TextField component. */
export type TextFieldVariant = 'filled' | 'outlined';

/**
 * Validation state shown to the user.
 * - `'none'`    — no special state (default colors).
 * - `'error'`   — M3 `error` (border/label/text/icon in `--md-sys-color-error`).
 * - `'success'` / `'warning'` — extension of this library
 *   (`--md-sys-color-success` / `--md-sys-color-warning`), not an official M3 role.
 */
export type TextFieldStatus = 'none' | 'error' | 'success' | 'warning';

/**
 * The single-line `<input>` types this library supports — a deliberate
 * subset of the native HTML `type` attribute, restricted to web's main
 * benefit over typing it manually: hinting the right virtual keyboard on
 * touch devices (e.g. `email`/`tel` swap in an `@`/numeric keypad).
 *
 * Excluded on purpose:
 * - `date`/`time`/`month`/`week`/`datetime-local`, `radio`, `checkbox`,
 *   `range`, `color`, `file` — each renders its own native widget instead
 *   of a text field, which the M3 filled/outlined visuals don't account
 *   for.
 * - `number` — adds native spinner arrows, also a visual mismatch; use
 *   `tel` (no spinners, still hints a numeric keypad) for phone-number-like
 *   input.
 * - `search` — adds the browser's own native clear ("x") button, which
 *   would duplicate/conflict with `trailingIcon` + `onTrailingIconClick`
 *   (already built into this component for exactly that use case).
 * - `submit`/`reset`/`button`/`image`/`hidden` — not text entry at all.
 */
export type TextFieldInputType = 'text' | 'email' | 'password' | 'tel' | 'url';

interface TextFieldBaseProps extends BaseComponentProps {
  /** Visual style of the field. Defaults to `'filled'`. */
  variant?: TextFieldVariant;
  /** Field label. Always visible (resting or floating) — required by M3. */
  label: string;
  /** Icon rendered before the input/textarea. Decorative. */
  leadingIcon?: ReactNode;
  /** Icon rendered after the input/textarea. */
  trailingIcon?: ReactNode;
  /**
   * When defined, `trailingIcon` is wrapped in an accessible
   * `<button type="button">` (clear, show/hide password, etc.).
   * Requires `trailingIconAriaLabel`.
   */
  onTrailingIconClick?: () => void;
  /** Accessible label for the button generated by `onTrailingIconClick`. */
  trailingIconAriaLabel?: string;
  /**
   * Help/error/success/warning text shown below the field.
   * Color and role (`alert`) are determined by `status`.
   */
  supportingText?: string;
  /** Validation state of the field. Defaults to `'none'`. */
  status?: TextFieldStatus;
  /** Shows "current length / maxLength" next to `supportingText`. Requires `maxLength`. */
  showCharacterCount?: boolean;
}

/**
 * Native attributes exclusive to one element, absent from the other.
 *
 * A plain discriminated union (`multiline?: false` vs `multiline: true`)
 * doesn't reject e.g. `rows` when `multiline` is omitted, because
 * TypeScript's excess-property check on unions only flags a property as
 * excess when it appears in *no* member — and `rows` is valid in the
 * `multiline: true` member. Intersecting each branch with
 * `Partial<Record<OtherBranchOnlyKey, never>>` closes that gap.
 */
type InputOnlyAttributes = Omit<
  InputHTMLAttributes<HTMLInputElement>,
  keyof TextareaHTMLAttributes<HTMLTextAreaElement>
>;
type TextareaOnlyAttributes = Omit<
  TextareaHTMLAttributes<HTMLTextAreaElement>,
  keyof InputHTMLAttributes<HTMLInputElement>
>;

export type TextFieldProps =
  | (TextFieldBaseProps & {
      /** `true` renders a `<textarea>` instead of an `<input>`. Defaults to `false`. */
      multiline?: false;
      /** Native `<input>` type, restricted to `TextFieldInputType`. Defaults to `'text'`. */
      type?: TextFieldInputType;
    } & Omit<InputHTMLAttributes<HTMLInputElement>, 'size' | 'type'> &
      Partial<Record<keyof TextareaOnlyAttributes, never>>)
  | (TextFieldBaseProps & {
      multiline: true;
    } & Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, 'size'> &
      Partial<Record<keyof InputOnlyAttributes, never>>);
